// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql_go_pets_example

// Page info for pagination
type PageInfo struct {
	StartCursor     *string `json:"startCursor"`
	EndCursor       *string `json:"endCursor"`
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
}

type PetInput struct {
	ID      *string `json:"id"`
	OwnerID string  `json:"ownerID"`
	Name    string  `json:"name"`
	TagIDs  []int   `json:"tagIDs"`
}

// Tag has everything needed for a tag
type Tag struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Pets  []*Pet `json:"pets"`
}

// what is needed for a user
type User struct {
	ID             string             `json:"id"`
	Name           string             `json:"name"`
	Pets           []*Pet             `json:"pets"`
	PetsConnection *UserPetConnection `json:"petsConnection"`
}

// The connection between users and pets
type UserPetConnection struct {
	TotalCount int            `json:"totalCount"`
	Edges      []*UserPetEdge `json:"edges"`
	PageInfo   *PageInfo      `json:"pageInfo"`
}

// The edge of the user pet connection
type UserPetEdge struct {
	Cursor string `json:"cursor"`
	Node   *Pet   `json:"node"`
}
